src/imdb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/movie/urls.py
from django.urls import path

from .views import MovieDetailView, MovieListView, MovieRecentListView, MovieTopListView, MovieMostListView, \
    MovieCategory, MovieLanguage, MovieSearch, MovieYear

app_name = 'movie'
urlpatterns = [
    path('', MovieListView.as_view(), name='movie-list'),
    path('category/<str:category>', MovieCategory.as_view(), name='movie-category'),
    path('language/<str:lang>', MovieLanguage.as_view(), name='movie-language'),
    path('search/', MovieSearch.as_view(), name='movie-search'),
    path('recent', MovieRecentListView.as_view(), name='movie-recent-list'),
    path('most', MovieMostListView.as_view(), name='movie-most-list'),
    path('top', MovieTopListView.as_view(), name='movie-top-list'),
    path('<slug:slug>', MovieDetailView.as_view(), name='movie-detail'),
    path('year/<int:year>', MovieYear.as_view(), name='movie-year'),
]

src/movie/models.py
from django.db import models


# Create your models here.
from django.utils import timezone
from django.utils.text import slugify


class Movie(models.Model):
    CATEGORY_CHOICES = (
        ('Action', 'ACTION'),
        ('Drama', 'DRAMA'),
        ('Comedy', 'COMEDY'),
        ('Romance', 'ROMANCE'),
        ('Horror', 'HORROR'),
    )
    LANGUAGE_CHOICES = (
        ('english', 'ENGLISH'),
        ('arabic', 'ARABIC')
    )
    STATUS_CHOICES = (
        ('R', 'RECENTLY ADDED'),
        ('M', 'MOST WATCHED'),
        ('T', 'TOP RATED')
    )
    title = models.CharField(max_length=255)
    description = models.TextField(max_length=1000)
    image = models.ImageField(upload_to='movies')
    category = models.CharField(max_length=8, choices=CATEGORY_CHOICES, default='Action')
    language = models.CharField(max_length=10, choices=LANGUAGE_CHOICES, default='english')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='R')
    cast = models.CharField(max_length=255)
    year_of_production = models.DateField()
    view_count = models.PositiveIntegerField(default=0)
    movie_trailer = models.URLField()
    slug = models.SlugField(blank=True, null=True)
    created = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.title
    
    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Movie, self).save(force_insert=False, force_update=False, using=None, update_fields=None)


class MovieLinks(models.Model):
    Link_CHOISES = (
        ('D', 'DOWNLOAD LINK'),
        ('W', 'WATCH LINK'),
    )
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE,
                              related_name='movie_watch_link')
    link = models.URLField()
    type = models.CharField(choices=Link_CHOISES, max_length=1, default='D')

    def __str__(self):
        return self.movie.title

src/movie/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.dates import YearArchiveView

from .models import Movie, MovieLinks


class MovieListView(ListView):
    model = Movie

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super(MovieListView, self).get_context_data()
        return ctx


class MovieRecentListView(MovieListView):
    queryset = Movie.objects.all().filter(status='R')


class MovieTopListView(MovieListView):
    queryset = Movie.objects.all().filter(status='T')


class MovieMostListView(MovieListView):
    queryset = Movie.objects.all().filter(status='M')


class MovieDetailView(DetailView):
    model = Movie

    def get_object(self, queryset=None):
        obj = super(MovieDetailView, self).get_object()
        return obj

    def get_context_data(self, **kwargs):
        ctx = super(MovieDetailView, self).get_context_data()
        ctx['links'] = MovieLinks.objects.filter(movie=self.get_object())
        movie = self.get_object()
        movie.view_count += 1
        movie.save()
        ctx['related_movies'] = Movie.objects.filter(
            category=self.get_object().category) #.order_by('created')[0:3]
        return ctx


class MovieCategory(ListView):
    model = Movie

    def dispatch(self, request, *args, **kwargs):
        self.category = self.kwargs['category']
        return super(MovieCategory, self).dispatch(request, *args, **kwargs)

    def __init__(self, **kwargs):
        super().__init__()
        self.category = None

    def get_queryset(self):
        return Movie.objects.filter(category=self.category)

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super(MovieCategory, self).get_context_data(**kwargs)
        ctx['movie_category'] = self.category
        return ctx


class MovieLanguage(ListView):
    model = Movie

    def dispatch(self, request, *args, **kwargs):
        self.language = self.kwargs['lang']
        return super(MovieLanguage, self).dispatch(request, *args, **kwargs)

    def __init__(self, **kwargs):
        super().__init__()
        self.language = None

    def get_queryset(self):
        return Movie.objects.filter(language=self.language)

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super(MovieLanguage, self).get_context_data(**kwargs)
        ctx['movie_language'] = self.language
        return ctx


class MovieSearch(ListView):
    model = Movie

    def get_queryset(self):
        query = self.request.GET.get('query')
        if query:
            object_list = self.model.objects.filter(title__icontains=query)
        else:
            object_list = self.model.objects.none()
        return object_list


class MovieYear(YearArchiveView):
    queryset = Movie.objects.all()
    date_field = 'year_of_production'
    make_object_list = True
    allow_future = True

src/movie/templates/movie/movie_archive_year.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
    <div id="main">

        <div id="content">
        {% if movie_language %}
        {{ movie_language }} Movies
        {% endif %}
            {% for movie in object_list %}
                <div class="box">
                <div class="movie">
                    <div class="movie-image">
                        {#                                      <span class="play"><span class="name">{{ movie.title }}</span></span>#}
                        <a href="{% url 'movie:movie-detail' movie.slug  %}">
                            <img src="{{ movie.image.url }}" alt="{{ movie.title }}"/></a></div>
                    <div class="rating">
                        <p>Category : {{ movie.category }}</p>
                        <span class="comments">{{ movie.view_count }}</span></div>
                </div>
                {% empty %}
                <h3>There are no Movie here</h3>
            {% endfor %}
            <div class="cl">&nbsp;</div>
            </div>


        </div>

    </div>

{% endblock %}

src/movie/templates/movie/movie_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <body>

    <div class="hero mv-single-hero">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- <h1> movie listing - list</h1>
                    <ul class="breadcumb">
                        <li class="active"><a href="#">Home</a></li>
                        <li> <span class="ion-ios-arrow-right"></span> movie listing</li>
                    </ul> -->
                </div>
            </div>
        </div>
    </div>
    <div class="page-single movie-single movie_single">
        <div class="container">

            <div class="col-md-8 col-sm-12 col-xs-12">
                <div class="movie-single-ct main-content">
                    <h1 class="bd-hd">{{ movie.title }} <span>{{ movie.year_of_production }}</span></h1>
                    <div class="row ipad-width2">
                        <div class="col-md-4 col-sm-12 col-xs-12">
                            <div class="movie-img sticky-sb">
                                <img src="{{ movie.image.url }}" alt="">


                                <div class="movie-btn">
                                    <div class="btn-transform transform-vertical red">
                                        <div><a href="{{ movie.movie_trailer }}" class="item item-1 redbtn"> <i
                                                class="ion-play"></i> Watch Trailer</a></div>
                                        <div><a href="{{ movie.movie_trailer }}"
                                                class="item item-2 redbtn fancybox-media hvr-grow"><i
                                                class="ion-play"></i></a></div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="movie-tabs">
                            <div class="tabs">
                                <ul class="tab-links tabs-mv">
                                    <p class="active" style="font-size:large ">{{ movie.category }} Movie</p>
                                    <br/>
                                    <p style="font-size: large"> Number of Views : {{ movie.view_count }} Views</p>
                                    <br/>
                                    {% for link in links %}
                                        <p style="font-size: large">
                                            {% if link.type == 'D' %}
                                                Download the Movie Now:
                                            {% elif link.type == 'W' %}
                                                To Watch the Movie here is the link:
                                                <a href="{{ link.link }}"> Watch</a>
                                            {% endif %}
                                        </p>
                                    {% endfor %}
<br>
                                    <h2> Related Movie</h2>
                                    {% for movie in related_movies %}
                                        <div class="box">
                                        <div class="movie">
                                            <div class="movie-image">

                                                <a href="{% url 'movie:movie-detail' movie.slug %}">
                                                    <img src="{{ movie.image.url }}" alt="{{ movie.title }}"/></a></div>
                                        </div>

                                    {% endfor %}
                                    </div>
                                </ul>
<br>
                                <div class="tab-content">
                                    <div id="overview" class="tab active">
                                        <div class="row">
                                            <div class="col-md-8 col-sm-12 col-xs-12">
                                                <h1><b> The Movie Description </b></h1>
                                                <h2 style="color: red; font-family: Chilanka; font-size: large">{{ movie.description }}    </h2>

                                            </div>

                                            <div class="title-hd-sm">
                                                <h2 style="font-size: 20px"> The Cast </h2>
                                                <div class="mvcast-item">
                                                    <div class="cast-it">
                                                        <div class="cast-left">
                                                           <strong> <p style="color: black"> {{ movie.cast }}</p></strong>
                                                        </div>

                                                    </div>

                                                </div>
                                            </div>

                                        </div>
                                    </div>

                                </div>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    </body>

{% endblock %}

src/movie/templates/movie/movie_list.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
    <div id="main">

        <div id="content">
        {% if movie_language %}
        {{ movie_language }} Movies
        {% endif %}
            {% for movie in object_list %}
                <div class="box">
                <div class="movie">
                    <div class="movie-image">
                        {#                                      <span class="play"><span class="name">{{ movie.title }}</span></span>#}
                        <a href="{% url 'movie:movie-detail' movie.slug %}">
                            <img src="{{ movie.image.url }}" alt="{{ movie.title }}"/></a></div>
                    <div class="rating">
                        <p>Category : {{ movie.category }}</p>
                        <span class="comments">{{ movie.view_count }}</span></div>
                </div>
                {% empty %}
                <h3>There are no Movie here</h3>
            {% endfor %}
            <div class="cl">&nbsp;</div>
            </div>

<div class="slideshow-container">
{% for movie in slider_movies %}
<div class="mySlides fade">
  <div class="numbertext">1 / {{ slider_movies.count }}</div>
  <img src="{{ movie.image.url }}" style="width:20%; height: 20%; size: auto" alt="{{ movie.title }}">
  <div class="text">{{ movie.title }}</div>
</div>
    {% endfor %}

<a class="prev" onclick="plusSlides(-1)">❮</a>
<a class="next" onclick="plusSlides(1)">❯</a>

</div>
        <br>

<div style="text-align:center">
  <span class="dot" onclick="currentSlide(1)"></span>
  <span class="dot" onclick="currentSlide(2)"></span>
  <span class="dot" onclick="currentSlide(3)"></span>
</div>
        </div>

    </div>
<script>
let slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  let i;
  let slides = document.getElementsByClassName("mySlides");
  let dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
}
</script>
{% endblock %}

src/templates/base.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    {% block title %}<title>MovieHunter</title> {% endblock %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<link  type="image/jpg" href="{% static 'images/favicon.gif' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all"/>
    <script type="text/javascript" src="{% static 'js/jquery-1.4.2.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-func.js' %}"></script>
    <!--[if IE 6]><link rel="stylesheet" href="{% static 'css/ie6.css' %}" type="text/css" media="all" /><![endif]-->
<style type="text/css">
    * {box-sizing: border-box}
body {font-family: Verdana, sans-serif; margin:0}
.mySlides {display: none}
img {vertical-align: middle;}

/* Slideshow container */
.slideshow-container {
  max-width: 1000px;
  position: relative;
  margin: auto;
}

/* Next & previous buttons */
.prev, .next {
  cursor: pointer;
  position: absolute;
  top: 50%;
  width: auto;
  padding: 16px;
  margin-top: -22px;
  color: white;
  font-weight: bold;
  font-size: 18px;
  transition: 0.6s ease;
  border-radius: 0 3px 3px 0;
  user-select: none;
}

/* Position the "next button" to the right */
.next {
  right: 0;
  border-radius: 3px 0 0 3px;
}

/* On hover, add a black background color with a little bit see-through */
.prev:hover, .next:hover {
  background-color: rgba(0,0,0,0.8);
}

/* Caption text */
.text {
  color: #f2f2f2;
  font-size: 15px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width: 100%;
  text-align: center;
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}

/* The dots/bullets/indicators */
.dot {
  cursor: pointer;
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbb;
  border-radius: 50%;
  display: inline-block;
  transition: background-color 0.6s ease;
}

.active, .dot:hover {
  background-color: #717171;
}

/* Fading animation */
.fade {
  animation-name: fade;
  animation-duration: 1.5s;
}

@keyframes fade {
  from {opacity: .4}
  to {opacity: 1}
}

/* On smaller screens, decrease text size */
@media only screen and (max-width: 300px) {
  .prev, .next,.text {font-size: 11px}
}

</style>
</head>

<body>
<!-- START PAGE SOURCE -->
<div id="shell">
    {% include 'header.html' %}

    {% block content %}{% endblock %}

    {% block js %} {% endblock %}



    {% include 'footer.html' %}
</div>
<!-- END PAGE SOURCE -->


</body>
</html>

src/templates/footer.html
  <div id="footer">
    <p class="lf">Copyright &copy;  {% now "Y" %}<a href="#"> Movies app</a> - All Rights Reserved</p>
    <p class="rf">For more info <a href = "mailto: mouiad.ali.work@gmail.com"> Momo</a></p>
    <div style="clear:both;"></div>
  </div>

src/templates/header.html
<style>
    ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #333;
    }

    li {
        float: left;
    }

    li a, .dropbtn {
        display: inline-block;
        color: red;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
    }

    li a:hover, .dropdown:hover .dropbtn {
        background-color: red;
    }

    li.dropdown {
        display: inline-block;

    }

    .dropdown-content {
        display: none;
        position: absolute;
        background-color: black;
        min-width: 160px;
        box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
        z-index: 4;
    }

    .dropdown-content a {
        color: black;
        padding: 12px 16px;
        text-decoration: none;
        display: block;
        text-align: left;
    }

    .dropdown-content a:hover {
        background-color: red;
    }

    .dropdown:hover .dropdown-content {
        display: block;
    }
</style>
<div id="header">
    <h1 id="logo"><a href="#">MovieHunter</a></h1>
    <div id="navigation">
        <ul>
            <li><a class="active" href="{% url 'movie:movie-list' %}">HOME</a></li>

        </ul>
    </div>
    <div id="sub-navigation">
        <ul>
            <li><a href="{% url 'movie:movie-recent-list' %}">RECENTLY ADDED</a></li>
            <li><a href="{% url 'movie:movie-most-list' %}">TOP RATED</a></li>
            <li><a href="{% url 'movie:movie-top-list' %}">MOST WATCHED</a></li>
            <li class="dropdown">
                <a href="javascript:void(0)" class="dropbtn">Category</a>
                <div class="dropdown-content">
                    <a href="{% url 'movie:movie-category' 'Action' %}">ACTION</a>
                    <a href="{% url 'movie:movie-category' 'Drama' %}">Drama</a>
                    <a href="{% url 'movie:movie-category' 'Comedy' %}">Comedy</a>
                    <a href="{% url 'movie:movie-category' 'Romance' %}">Romance</a>
                    <a href="{% url 'movie:movie-category' 'Horror' %}">Horror</a>
                </div>
            </li>
            <li class="dropdown">
                <a href="javascript:void(0)" class="dropbtn">Movie languages</a>
                <div class="dropdown-content">
                    <a href="{% url 'movie:movie-language' 'english' %}">EN</a>
                    <a href="{% url 'movie:movie-language' 'arabic' %}">Ar</a>
                </div>
            </li>
     <li class="dropdown">
                <a href="javascript:void(0)" class="dropbtn">Year</a>
                <div class="dropdown-content">
                    <a href="{% url 'movie:movie-year' '2014' %}">2014</a>
                    <a href="{% url 'movie:movie-year' '2015' %}">2015</a>
                    <a href="{% url 'movie:movie-year' '2016' %}">2016</a>
                    <a href="{% url 'movie:movie-year' '2017' %}">2017</a>
                    <a href="{% url 'movie:movie-year' '2018'%}">2018</a>
                    <a href="{% url 'movie:movie-year' '2019' %}">2019</a>
                    <a href="{% url 'movie:movie-year' '2020' %}">2020</a>
                    <a href="{% url 'movie:movie-year' '2021'%}">2021</a>
                    <a href="{% url 'movie:movie-year' '2022'%}">2022</a>
                </div>
            </li>
        </ul>
        <div id="search">
            <form action="{% url 'movie:movie-search' %}" method="GET" accept-charset="utf-8">
                <label for="search-field">SEARCH</label>
                <input type="text" name="query" value="{{ request.GET.q }}" id="search-field"
                       class="blink search-field"/>
                <input type="submit" value="GO!" class="search-button"/>
            </form>
        </div>
    </div>
</div>